In [1]:
import numpy as np


In [2]:
for i in range(1, 1):
    print("hello world!")

In [3]:
X = np.array([[1, 2], [3, 4]])

In [4]:
dists = -2 * X @ X.T + np.sum(X**2, axis = 1) + np.sum(X**2, axis = 1)[:, np.newaxis]

In [5]:
dists

array([[0, 8],
       [8, 0]])

In [6]:
np.sum(X**2, axis = 1)[:, np.newaxis]

array([[ 5],
       [25]], dtype=int32)

In [7]:
np.sum(X**2, axis = 1)

array([ 5, 25], dtype=int32)